# Generated by Django 3.2.23 on 2024-02-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='email',
            field=models.EmailField(default='sem_email@example.com', max_length=254),
        ),
    ]
