# Generated by Django 4.0.6 on 2024-06-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_alter_receita_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
