# Generated by Django 4.0.6 on 2024-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_receita_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='complemento_ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='complemento_modo_preparo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
