# Generated by Django 4.0.6 on 2024-08-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0012_receita_complemento_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='complemento_ingredientes',
        ),
    ]
