# Generated by Django 3.2.19 on 2025-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0013_remove_receita_complemento_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='isAproved',
            field=models.BooleanField(default=False),
        ),
    ]
